environment:

  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

install:
  - "%MINICONDA%\\Scripts\\activate"
  - conda config --set always_yes yes
  - conda create -q -n test_env python=%PYTHON_VERSION%
  - activate test_env
  - echo CONDA_PREFIX %CONDA_PREFIX%
  - echo PATH %PATH%
  - conda config --append channels conda-forge
  - conda install qutip
  - pip install .[dev]
  - pip freeze

build: off

test_script:
  - ps: pytest --doctest-modules --cov=newtonprop --nbval --sanitize-with docs\nbval_sanitize.cfg src tests (get-item docs\*.rst).FullName docs\example.ipynb
