name: rtdvenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip:
    - better-apidoc>=0.2.0
    - sphinx_autodoc_typehints
    - sphinxcontrib-bibtex
    - nbsphinx
    - gitpython
