name: binder
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - qutip=4.3.1
  - pip:
    - matplotlib
    - watermark
    - git+https://github.com/qucontrol/newtonprop.git@master#egg=newtonprop
